apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
        - name: config-map
          configMap:
            name: log-output-configmap
            items:
              - key: "information.txt"
                path: "information.txt"
      containers:
        - name: log-output-reader
          image: log-output-reader:1.00
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PINGPONG_URL
              value: http://pingpong-svc:1234/pingpong
            - name: OUTPUT_FILE
              value: /usr/src/app/files/outputFile.txt
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: message

          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
            - name: config-map
              mountPath: /app/config
              readOnly: true


        - name: log-output-writer
          image: log-output-writer:1.00
          imagePullPolicy: IfNotPresent
          env:
            - name: OUTPUT_FILE
              value: /usr/src/app/files/outputFile.txt
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
