apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: log-pong-pvc
      containers:
        - name: pingpong
          image: ping-pong:1.01
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: PONG_FILE
              value: /usr/src/app/files/pongFile.txt
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files

