apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-project-pvc
  namespace: project
spec:
  storageClassName: dwk-the-project-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi