spring:
  main:
    banner-mode: OFF

  application:
    name: the_project

server:
  port: ${PORT}

logging:
  level:
    root: warn

app:
  image:
    image-file: ${IMAGE_FILE}
    timestamp-file: ${TIMESTAMP_FILE}
    image-url: ${IMAGE_URL}
    image-ttl-minutes: ${IMAGE_TTL_MINUTES}